### ISSUE TITLE
glitch: time_label_for_uuid results in an exception but not a failure

### ISSUE THREAD

**Issue by djhoese** [ssec/sift#105]
In GitLab by @rayg-ssec on Oct 30, 2015, 13:33

```Traceback (most recent call last):
  File "/Users/keoni/Repos/git/CSPOV/py/cspov/__main__.py", line 256, in update_frame_time_to_top_visible
    self.ui.animationLabel.setText(self.document.time_label_for_uuid(self.scene_manager.layer_set.top_layer_uuid()))
  File "/Users/keoni/Repos/git/CSPOV/py/cspov/model/document.py", line 242, in time_label_for_uuid
    info = self._layer_with_uuid[uuid]
KeyError: None
INFO:__main__:band incr 1
Traceback (most recent call last):
  File "/Users/keoni/Repos/git/CSPOV/py/cspov/__main__.py", line 256, in update_frame_time_to_top_visible
    self.ui.animationLabel.setText(self.document.time_label_for_uuid(self.scene_manager.layer_set.top_layer_uuid()))
  File "/Users/keoni/Repos/git/CSPOV/py/cspov/model/document.py", line 242, in time_label_for_uuid
    info = self._layer_with_uuid[uuid]
KeyError: None```

**Comment by djhoese** [comment]
In GitLab by @rayg-ssec on Nov 3, 2015, 07:27

This should be fixed in 0.7.
