### ISSUE TITLE
current version of vispy fails to freeze with py2exe

### ISSUE THREAD

**Issue by djhoese** [ssec/sift#135]
In GitLab by @djhoese on Dec 7, 2015, 10:52

I'm attempting to package up SIFT which depends on vispy. While trying to perform the basic py2exe build process:

    # in setup.py
    import py2exe
    # add to setup call
    console=[{
        'script': 'cspov/__main__.py',
        'dest_base': "SIFT",
        }],

Then running `python setup.py py2exe` on a Windows Virtual Machine I get the following error when trying to run the produced SIFT.exe executable:

    [sift_py2exe] C:\Users\User\repos\git\CSPOV\py\dist>SIFT.exe
    Traceback (most recent call last):
      File "__main__.py", line 24, in <module>
      File "C:\Anaconda3\envs\sift_py2exe\lib\site-packages\vispy\__init__.py", line 30, in <module>
        from .util import config, set_log_level, keys, sys_info  # noqa
      File "C:\Anaconda3\envs\sift_py2exe\lib\site-packages\vispy\util\__init__.py", line 9, in <module>
        from .logs import logger, set_log_level, use_log_level  # noqa
      File "C:\Anaconda3\envs\sift_py2exe\lib\site-packages\vispy\util\logs.py", line 16, in <module>
        from ..ext.six import string_types
      File "C:\Anaconda3\envs\sift_py2exe\lib\site-packages\vispy\ext\six.py", line 67, in <module>
        _import_six()
      File "C:\Anaconda3\envs\sift_py2exe\lib\site-packages\vispy\ext\six.py", line 64, in _import_six
        "distribution.".format(_SIX_MIN_VERSION))
    ImportError: Vispy requires the 'six' module of minimum version 1.4.1; normally
    this is bundled with the Vispy package so if you get this warning consult the pa
    ckager of your Vispy distribution.

Apparently this has been fixed in a newer commit of vispy than what we are using in the larch "cspov" channel: https://github.com/vispy/vispy/pull/1136

I will try updating to the newest commit at time of writing and see what breaks. The old commit was `65edc3245aaf1e2e55d60d9c3c4abb68564b5972` and the new commit is `236fa011ef5d57fecb3ab96a1d97bf8e1b08f2b7`.

**Comment by djhoese** [comment]
In GitLab by @djhoese on Apr 4, 2016, 12:54

Found a workaround by using pyinstaller instead, although the newer version of vispy did help I ran in to too many issues as I continued (can't remember specifics).
