### ISSUE TITLE
GOES-17 layer details, color enhancement

### ISSUE THREAD

**Issue by djhoese** [ssec/sift#191]
In GitLab by @jgerth on Jul 23, 2018, 12:03

GOES-17 B02 and B03 data is not being loaded with a central wavelength in the layer details or the correct color enhancement (which should be "Square Root"). I have not attempted loading other bands.

It reports the following load error:
`ERROR 11:37:38 queue:run:L82 Background task exception: 
Traceback (most recent call last):
  File "/Users/jordang/anaconda/envs/sift/lib/python3.6/site-packages/sift/queue.py", line 78, in run
    for status in task:
  File "/Users/jordang/anaconda/envs/sift/lib/python3.6/site-packages/sift/__main__.py", line 264, in _bgnd_open_paths
    for progress in self.document.import_files(paths, **importer_kwargs):
  File "/Users/jordang/anaconda/envs/sift/lib/python3.6/site-packages/sift/model/document.py", line 1573, in import_files
    self.activate_product_uuid_as_new_layer(uuid, insert_before=insert_before, **importer_kwargs)
  File "/Users/jordang/anaconda/envs/sift/lib/python3.6/site-packages/sift/model/document.py", line 1460, in activate_product_uuid_as_new_layer
    self._add_layer_family(dataset)
  File "/Users/jordang/anaconda/envs/sift/lib/python3.6/site-packages/sift/model/document.py", line 1496, in _add_layer_family
    self.didAddFamily.emit(family, self.family_info(family))
  File "/Users/jordang/anaconda/envs/sift/lib/python3.6/site-packages/sift/model/document.py", line 1530, in family_info
    INFO.UNITS: family_rep[INFO.UNITS],
  File "/Users/jordang/anaconda/envs/sift/lib/python3.6/collections/__init__.py", line 885, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/Users/jordang/anaconda/envs/sift/lib/python3.6/collections/__init__.py", line 877, in __missing__
    raise KeyError(key)
KeyError: <INFO.UNITS: 'units'>
Traceback (most recent call last):
  File "/Users/jordang/anaconda/envs/sift/lib/python3.6/site-packages/sift/queue.py", line 183, in _did_complete_task
    todo(succeeded)
  File "/Users/jordang/anaconda/envs/sift/lib/python3.6/site-packages/sift/__main__.py", line 278, in _bgnd_open_paths_finish
    raise ValueError("background open did not succeed")
ValueError: background open did not succeed`

**Comment by djhoese** [comment]
In GitLab by @rayg-ssec on Jul 25, 2018, 13:39

assigned to @rayg-ssec

**Comment by djhoese** [comment]
In GitLab by @rayg-ssec on Jul 25, 2018, 13:42

Updated guidebook for H9 and G17. Testing this afternoon before pushing to develop...

**Comment by djhoese** [comment]
In GitLab by @rayg-ssec on Jul 25, 2018, 15:06

mentioned in commit aab0c02a4c1f23f18c8bd27ff869de1707bc58ad

**Comment by djhoese** [comment]
In GitLab by @rayg-ssec on Jul 25, 2018, 15:08

Confirmed that there's no exception and the detail view for G17 shows sqrt enhancement and matches G16 for nominal wavelength.

**Comment by djhoese** [comment]
In GitLab by @rayg-ssec on Jul 25, 2018, 16:09

Closing this as solution verified in develop branch, re-open if the issue shows up again.

**Comment by djhoese** [comment]
In GitLab by @rayg-ssec on Jul 25, 2018, 16:09

closed
