### ISSUE TITLE
Background database scrubbing can take long enough that timeline access to MDB fails

### ISSUE THREAD

**Issue by djhoese** [ssec/sift#194]
In GitLab by @rayg-ssec on Jul 30, 2018, 11:48

- Load metadatabase with ~2000 products, only a few of which are to remain after purge
- stop sift, move directory with most products elsewhere (or unmount)
- restart sift, get an possible exception due to conflict between database cleaning and database use for timeline:

```
INFO 11:41:45 workspace:_purge_orphan_products:L419 discarding orphaned product <Product 'B11' @ 2017-05-03 00:54:58.300000~2017-05-03 00:55:04 / 30 keys>
WARNING 11:41:45 metadatabase:__exit__:L748 an exception occurred, rolling back any metadatabase changes
Traceback (most recent call last):
  File "/Users/keoni/anaconda/envs/sift36/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/Users/keoni/anaconda/envs/sift36/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
INFO 11:41:45 workspace:_purge_orphan_products:L419 discarding orphaned product <Product 'B11' @ 2017-05-03 00:55:58.300000~2017-05-03 00:56:04 / 30 keys>
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/keoni/anaconda/envs/sift36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/keoni/anaconda/envs/sift36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/keoni/Repos/git/sift/sift/__main__.py", line 1084, in <module>
    sys.exit(main())
  File "/Users/keoni/Repos/git/sift/sift/__main__.py", line 1073, in main
    center=args.center,
  File "/Users/keoni/Repos/git/sift/sift/__main__.py", line 749, in __init__
    self._init_timeline(doc, self.workspace)
  File "/Users/keoni/Repos/git/sift/sift/__main__.py", line 571, in _init_timeline
    self._timeline_scene.sync_items()
  File "/Users/keoni/Repos/git/sift/sift/control/doc_ws_as_timeline_scene.py", line 319, in sync_items
INFO 11:41:45 workspace:_purge_orphan_products:L419 discarding orphaned product <Product 'B11' @ 2017-05-03 00:56:58.300000~2017-05-03 00:57:04 / 30 keys>
    self._invalidate()
  File "/Users/keoni/Repos/git/sift/sift/control/doc_ws_as_timeline_scene.py", line 164, in _invalidate
    self._sync_tracks_frames()
  File "/Users/keoni/Repos/git/sift/sift/control/doc_ws_as_timeline_scene.py", line 115, in _sync_tracks_frames
    for z, trk in self._doc.enumerate_tracks_frames():
  File "/Users/keoni/Repos/git/sift/sift/model/document.py", line 677, in enumerate_tracks_frames
    for prod in que.all():
  File "/Users/keoni/anaconda/envs/sift36/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2703, in all
INFO 11:41:45 workspace:_purge_orphan_products:L419 discarding orphaned product <Product 'B11' @ 2017-05-03 00:57:58.300000~2017-05-03 00:58:04 / 30 keys>
    return list(self)
  File "/Users/keoni/anaconda/envs/sift36/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
    return self._execute_and_instances(context)
  File "/Users/keoni/anaconda/envs/sift36/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/Users/keoni/anaconda/envs/sift36/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/Users/keoni/anaconda/envs/sift36/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
INFO 11:41:45 workspace:_purge_orphan_products:L419 discarding orphaned product <Product 'B11' @ 2017-05-03 00:58:58.300000~2017-05-03 00:59:04 / 30 keys>
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/keoni/anaconda/envs/sift36/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/keoni/anaconda/envs/sift36/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/Users/keoni/anaconda/envs/sift36/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/Users/keoni/anaconda/envs/sift36/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/keoni/anaconda/envs/sift36/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
INFO 11:41:45 workspace:_purge_orphan_products:L419 discarding orphaned product <Product 'B11' @ 2017-05-03 00:59:58.300000~2017-05-03 01:00:04.200000 / 30 keys>
    raise value.with_traceback(tb)
  File "/Users/keoni/anaconda/envs/sift36/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/Users/keoni/anaconda/envs/sift36/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
```

* [x] look at options for mitigating context-sessions generating exceptions instead of serializing

**Comment by djhoese** [comment]
In GitLab by @rayg-ssec on Jul 30, 2018, 14:24

more information at http://docs.sqlalchemy.org/en/rel_0_9/dialects/sqlite.html#database-locking-behavior-concurrency

**Comment by djhoese** [comment]
In GitLab by @rayg-ssec on Jul 30, 2018, 15:12

marked the task **look at options for mitigating context-sessions generating exceptions instead of serializing** as completed

**Comment by djhoese** [comment]
In GitLab by @rayg-ssec on Jul 30, 2018, 15:12

After trying a number of solutions, went back to doing this startup maintenance in the main thread, which is ugly but at least not crashy. Ref ec5766221533d870399d3b41139f402c5c311392

**Comment by djhoese** [comment]
In GitLab by @rayg-ssec on Jul 30, 2018, 15:12

closed
