### ISSUE TITLE
Layer not created for algebraic composite

### ISSUE THREAD

**Issue by djhoese** [ssec/sift#199]
In GitLab by @jgerth on Sep 4, 2018, 16:53

A new layer is not created when the user attempts to produce an algebraic composite.

To reproduce: Load at least two ABI bands, select "Create Algebraic" from the "Layer" menu, type a name (e.g., "DIFF"), and select "OK". A new layer with the difference is not created.

Instead this error is reported:
```INFO 16:24:06 document:create_algebraic_composite:L2068 Creating algebraic layer 'DIFF' for time 2017-02-09 17:37:00
WARNING 16:24:08 workspace:_update_mask:L206 mask_from_coverage_sparsity needs inclusion
WARNING 16:24:08 metadatabase:__exit__:L748 an exception occurred, rolling back any metadatabase changes
Traceback (most recent call last):
  File "/Users/jordang/anaconda3/envs/sift/lib/python3.6/site-packages/sift/view/create_algebraic.py", line 147, in _create_algebraic
    self.doc.create_algebraic_composite(operations=operations, namespace=namespace, info=info)
  File "/Users/jordang/anaconda3/envs/sift/lib/python3.6/site-packages/sift/model/document.py", line 2070, in create_algebraic_composite
    uuid, layer_info, data = self._workspace.create_algebraic_composite(operations, temp_namespace, info.copy())
  File "/Users/jordang/anaconda3/envs/sift/lib/python3.6/site-packages/sift/workspace/workspace.py", line 1072, in create_algebraic_composite
    codeblock=operations)
  File "/Users/jordang/anaconda3/envs/sift/lib/python3.6/site-packages/sift/workspace/workspace.py", line 1129, in _create_product_from_array
    return uuid, self.get_info(uuid), overview_data
  File "/Users/jordang/anaconda3/envs/sift/lib/python3.6/site-packages/sift/workspace/workspace.py", line 617, in get_info
    native_content = self._product_native_content(s, kind=kind, uuid=dsi_or_uuid)
  File "/Users/jordang/anaconda3/envs/sift/lib/python3.6/site-packages/sift/workspace/workspace.py", line 545, in _product_native_content
    return contents[-1]
IndexError: list index out of range
```

**Comment by djhoese** [comment]
In GitLab by @djhoese on Sep 5, 2018, 11:16

Good news: I can reproduce this. Bad news: Not sure why it is happening.

**Comment by djhoese** [comment]
In GitLab by @djhoese on Sep 5, 2018, 11:16

assigned to @djhoese

**Comment by djhoese** [comment]
In GitLab by @djhoese on Sep 5, 2018, 11:16

assigned to @rayg-ssec and unassigned @djhoese

**Comment by djhoese** [comment]
In GitLab by @djhoese on Sep 5, 2018, 11:16

assigned to @djhoese and unassigned @rayg-ssec

**Comment by djhoese** [comment]
In GitLab by @djhoese on Oct 25, 2018, 13:04

As far as I know this has been fixed. @jgerth please reopen and let me know if this is still an issue in 1.0.0.

**Comment by djhoese** [comment]
In GitLab by @djhoese on Oct 25, 2018, 13:04

closed
