### ISSUE TITLE
No contours for field from GFS GRIB2

### ISSUE THREAD

**Issue by djhoese** [ssec/sift#202]
In GitLab by @jgerth on Oct 8, 2018, 05:16

I loaded the PWAT (precipitable water) field from a GFS GRIB2 analysis file. The image displays fine but there do not seem to be any contours. Also, the probe in the layer list does not return any value, regardless if it is a contour or image. I am testing on MacOS using the conda release.

**Comment by djhoese** [comment]
In GitLab by @djhoese on Oct 8, 2018, 07:59

Can you point me to the exact file you were looking at? Are you sure the data is valid? Were there any new error messages on the terminal related to this?

**Comment by djhoese** [comment]
In GitLab by @jgerth on Oct 8, 2018, 10:02

Sure: http://www.ftp.ncep.noaa.gov/data/nccf/com/gfs/prod/gfs.2018100400/gfs.t00z.pgrb2.0p50.anl

I am sure the data is valid, but when I went back to look for error messages, it would not reload it at all. Instead:

```
INFO 21:58:38 __main__:open_wizard:L855 Loading products from open wizard...
INFO 21:58:38 __main__:_bgnd_open_paths:L264 opening products from 1 paths in background
INFO 21:58:38 workspace:import_product_content:L910 product already has content available, using that rather than re-importing
WARNING 21:58:38 metadatabase:__exit__:L748 an exception occurred, rolling back any metadatabase changes
ERROR 21:58:38 queue:run:L82 Background task exception: 
Traceback (most recent call last):
  File "/Users/jordang/anaconda3/envs/sift/lib/python3.6/site-packages/sift/queue.py", line 78, in run
    for status in task:
  File "/Users/jordang/anaconda3/envs/sift/lib/python3.6/site-packages/sift/__main__.py", line 265, in _bgnd_open_paths
    for progress in self.document.import_files(paths, **importer_kwargs):
  File "/Users/jordang/anaconda3/envs/sift/lib/python3.6/site-packages/sift/model/document.py", line 1590, in import_files
    self.activate_product_uuid_as_new_layer(uuid, insert_before=insert_before, **importer_kwargs)
  File "/Users/jordang/anaconda3/envs/sift/lib/python3.6/site-packages/sift/model/document.py", line 1461, in activate_product_uuid_as_new_layer
    active_content_data = self._workspace.import_product_content(uuid, **importer_kwargs)
  File "/Users/jordang/anaconda3/envs/sift/lib/python3.6/site-packages/sift/workspace/workspace.py", line 912, in import_product_content
    assert (ovc is not None)
AssertionError
Traceback (most recent call last):
  File "/Users/jordang/anaconda3/envs/sift/lib/python3.6/site-packages/sift/queue.py", line 183, in _did_complete_task
    todo(succeeded)
  File "/Users/jordang/anaconda3/envs/sift/lib/python3.6/site-packages/sift/__main__.py", line 279, in _bgnd_open_paths_finish
    raise ValueError("background open did not succeed")
ValueError: background open did not succeed
```

Thanks for investigating.

**Comment by djhoese** [comment]
In GitLab by @djhoese on Oct 25, 2018, 13:02

This has been fixed by me adding more default contour intervals for more standard_names and various units. Still not the best approach but we'll have to work on that more in the future.

**Comment by djhoese** [comment]
In GitLab by @djhoese on Oct 25, 2018, 13:02

closed
