### ISSUE TITLE
Unable to delete RGB composite; unable to reload band from RGB

### ISSUE THREAD

**Issue by djhoese** [ssec/sift#205]
In GitLab by @jgerth on Oct 18, 2018, 18:12

This issue uses these three Himawari files to replicate:

C05: ftp://ftp.ssec.wisc.edu/pub/ssec/jordang/OT_AHI-L2-CMIPHFD-M1C05_H8_s20182770000208_e20182770009402_c20182770819110.nc
C10: ftp://ftp.ssec.wisc.edu/pub/ssec/jordang/OT_AHI-L2-CMIPHFD-M1C10_H8_s20182770000198_e20182770009392_c20182770819126.nc
C13: ftp://ftp.ssec.wisc.edu/pub/ssec/jordang/OT_AHI-L2-CMIPHFD-M1C13_H8_s20182770000208_e20182770009402_c20182770819147.nc

1. I loaded the above files using the 'Open...' menu option.
2. I created an RGB composite using C05 in the red component.
3. I deleted the three bands.
4. **Bug 1:** I attempt to remove the RGB composite as a layer. It does not delete.
5. **Bug 2:** I attempt to reload the bands. Only C10 and C13 load. I still cannot remove the RGB composite. This is the error message:
```INFO 18:09:24 __main__:_bgnd_open_paths:L265 opening products from 3 paths in background
WARNING 18:09:24 document:import_files:L1594 layer with UUID cc8039c6-d30e-11e8-9f5f-acbc3287257d already in document?
WARNING 18:09:24 document:import_files:L1594 layer with UUID cc7c5b12-d30e-11e8-8bcf-acbc3287257d already in document?
WARNING 18:09:24 document:import_files:L1594 layer with UUID cc74dba8-d30e-11e8-bb22-acbc3287257d already in document?
ERROR 18:09:24 layer_tree:select:L374 UUID cc74dba8-d30e-11e8-bb22-acbc3287257d cannot be selected in list view
INFO 18:09:24 document:animate_siblings_of_layer:L2450 no time siblings to chosen band, will try channel siblings to chosen time
Traceback (most recent call last):
  File "/Users/jordang/anaconda3/envs/sift/lib/python3.6/site-packages/sift/queue.py", line 183, in _did_complete_task
    todo(succeeded)
  File "/Users/jordang/anaconda3/envs/sift/lib/python3.6/site-packages/sift/__main__.py", line 284, in _bgnd_open_paths_finish
    self.document.animate_siblings_of_layer(uuid)
  File "/Users/jordang/anaconda3/envs/sift/lib/python3.6/site-packages/sift/model/document.py", line 2457, in animate_siblings_of_layer
    L.animation_order = new_anim_uuids
  File "/Users/jordang/anaconda3/envs/sift/lib/python3.6/site-packages/sift/model/document.py", line 267, in animation_order
    self._store[idx] = self._store[idx]._replace(a_order=nth)
TypeError: list indices must be integers or slices, not NoneType
```

Thanks for investigating.

**Comment by djhoese** [comment]
In GitLab by @jgerth on Oct 18, 2018, 18:13

changed the description

**Comment by djhoese** [comment]
In GitLab by @jgerth on Oct 18, 2018, 18:13

changed the description

**Comment by djhoese** [comment]
In GitLab by @jgerth on Oct 18, 2018, 18:14

changed the description

**Comment by djhoese** [comment]
In GitLab by @jgerth on Oct 18, 2018, 18:16

changed the description

**Comment by djhoese** [comment]
In GitLab by @jgerth on Oct 18, 2018, 18:16

changed the description

**Comment by djhoese** [comment]
In GitLab by @djhoese on Oct 19, 2018, 07:45

I'll try this out. I have a feeling the deletion issues you first had were causing all the later issues. It looks like these error messages are for the reloading step, not the deletion step. I also wouldn't be surprised if this is due to the timing issues mentioned on slack. That or if these had been loaded in previous versions of SIFT and something may have changed.

**Comment by djhoese** [comment]
In GitLab by @djhoese on Oct 19, 2018, 11:54

This has all been fixed in the most recent develop branch and will be released in 1.0.0b6

**Comment by djhoese** [comment]
In GitLab by @djhoese on Oct 19, 2018, 11:54

closed

**Comment by djhoese** [comment]
In GitLab by @rayg-ssec on Oct 19, 2018, 15:27

mentioned in commit f45b32a02d9c0c588862dfb5766d8d06f235c2e2
