### ISSUE TITLE
SIFT_1.0.6.dmg not opening

### ISSUE THREAD

**Issue by joleenf** [ssec/sift#242]
Hi,

I had a SIFT Beta 0.9.1 on my mac.  I wanted to update, but the current dmg seems to install.  However, verifying that I really want to open this app from an unknown developer, no interface appears after the verification process.  I am using the dmg currently linked here ftp://ftp.ssec.wisc.edu/pub/sift/dist/SIFT_1.0.6.dmg

Joleen

**Comment by djhoese** [comment]
Try right clicking on the .app and choosing "Open". If I recall correctly this is a security measure by OSX to not let you accidentally double click an untrusted .app. After you do it the first time it *should* allow for double clicking.

**Comment by joleenf** [comment]
Hi Dave,

That is what I did, and after verifying and looking like it should open (SIFT icon bounces a few times), no interface opens.  

Joleen

**Comment by djhoese** [comment]
Can you try navigating to the location of the `.app` in Terminal.app and doing `open -a SIFT.app`. It should give you an error message on the terminal.

**Comment by joleenf** [comment]
LSOpenURLsWithRole() failed for the application /Applications/SIFT.app with error -10810.

**Comment by djhoese** [comment]
@rayg-ssec Any ideas? I don't think I've ever seen this error before.

**Comment by joleenf** [comment]
Could it be a bad uninstall of the previous version?  I just moved the previous version to trash, rather than replacing old with new version.

**Comment by djhoese** [comment]
@joleenf You could also try, from the terminal, running `./SIFT.app/Contents/MacOS/SIFT` (I think that's the executable path).

Moving the old version to Trash *should* be fine. It is possible that the "workspace" needs to be deleted. I forget where it is by default (`~/Library/Application Support/SIFT/workspace` maybe), but if you delete that directory and try opening SIFT maybe that will help.

**Comment by joleenf** [comment]
Hi,

The sift_workspace I found was in my Documents folder.  This is the error I got when entering ./SIFT.app/Contents/MacOS/SIFT

Traceback (most recent call last):
  File "site-packages/PyInstaller/loader/rthooks/pyi_rth_qt4plugins.py", line 41, in <module>
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/PyInstaller/loader/rthooks/pyi_rth_qt4plugins.py", line 43, in <module>
ImportError: dlopen(/Applications/SIFT.app/Contents/MacOS/PyQt4/QtCore.so, 2): Library not loaded: @loader_path/libc++.1.dylib
  Referenced from: /Applications/SIFT.app/Contents/MacOS/libc++.1.dylib
  Reason: image not found
[4072] Failed to execute script pyi_rth_qt4plugins

**Comment by djhoese** [comment]
Did you have it installed in `/Applications` before? If not, what if you install SIFT in `~/Applications`?

**Comment by rayg-ssec** [comment]
If I remember correctly, Jess may have tried running it straight out of the DMG instead of dragging it into /Applications or ~/Applications? In the training haze I forgot that it's Windows that needs an installer, Mac is the usual drag-to-install.


On 2019.10.08, at 15:13, David Hoese <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you have it installed in /Applications before? If not, what if you install SIFT in ~/Applications?

**Comment by joleenf** [comment]
Hi Dave,

Same error:  
(satpy) simple:Applications joleenf$ pwd
/Users/joleenf/Applications

(satpy) simple:Applications joleenf$ ./SIFT.app/Contents/MacOS/SIFT
Traceback (most recent call last):
  File "site-packages/PyInstaller/loader/rthooks/pyi_rth_qt4plugins.py", line 41, in <module>
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/PyInstaller/loader/rthooks/pyi_rth_qt4plugins.py", line 43, in <module>
ImportError: dlopen(/Users/joleenf/Applications/SIFT.app/Contents/MacOS/PyQt4/QtCore.so, 2): Library not loaded: @loader_path/libc++.1.dylib
  Referenced from: /Users/joleenf/Applications/SIFT.app/Contents/MacOS/libc++.1.dylib
  Reason: image not found
[4796] Failed to execute script pyi_rth_qt4plugins
(satpy) simple:Applications joleenf$

**Comment by joleenf** [comment]
Running straight from the dmg and get the same error in terminal.
