### ISSUE TITLE
AttributeError and core dump when removing file from selection dialogue

### ISSUE THREAD

**Issue by gerritholl** [ssec/sift#253]
I'm getting a reproducable crash with an `AttributeError` followed by `Aborted (core dumped)` when I try to remove a file from the selection dialogue.  To reproduce:

* install from https://github.com/katherinekolman/sift/commit/2f36231ae3688ad8b3c934bfbd6f657b17fa2ab4
* start `python -m uwsift`
* `File` -> `Open File Wizard`
* Under Reader, select `GOES-R ABI Level 1b`
* Click `+` (Add files/dirs to list)
* Load multiple files, in this case GOES ABI L1B Meso 1 files.

![Screenshot of file selection dialogue](https://user-images.githubusercontent.com/500246/68201244-b57ab680-ffc1-11e9-9a97-aab80a0280a4.png)

* In File wizard, select one of the files
* Click `-`

At this point, the windows all close and the console shows an `AttributeError` and a `Aborted (core dumped)` message.

Full output to stderr with some logging enabled:

```
INFO 11:38:07 __init__:check_grib_definition_dir:L41 Setting GRIB definition path to /media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/uwsift/data/grib_definitions:/media/nas/x21324/miniconda3/envs/py37_sandbox/share/eccodes/definitions
INFO 11:38:07 __main__:main:L1175 Using configuration directory: /home/gholl/.config/SIFT/settings
INFO 11:38:07 __main__:main:L1176 Using cache directory: None
WARNING: Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
WARNING 11:38:07 _qt:message_handler:L180 Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
INFO 11:38:08 __main__:main:L1188 will search [] for new data periodically
INFO 11:38:08 workspace:__init__:L355 attaching pre-existing workspace at /home/gholl/.cache/SIFT/workspace
INFO 11:38:08 workspace:_init_create_workspace:L375 attaching database at /home/gholl/.cache/SIFT/workspace/_inventory.db
INFO 11:38:08 metadatabase:connect:L752 attaching database at sqlite:////home/gholl/.cache/SIFT/workspace/_inventory.db
INFO 11:38:08 workspace:_init_create_workspace:L380 done with init
INFO 11:38:09 workspace:_purge_inaccessible_resources:L431 discarded metadata for 0 orphaned resources
INFO 11:38:10 workspace:_purge_orphan_products:L446 discarded metadata for 0 orphaned products
INFO 11:38:15 document:sync_potential_tracks_from_metadata:L1382 went from 0 available tracks to 17
INFO 11:38:16 scene_graph:change_tool:L851 Changing tool to 'Tool.PAN_ZOOM'
INFO 11:38:16 visuals:__init__:L1122 Loading boundaries: 2019-11-05 10:38:16.262401
INFO 11:38:16 visuals:__init__:L1154 Done loading boundaries: 2019-11-05 10:38:16.352618
INFO 11:38:16 visuals:__init__:L1122 Loading boundaries: 2019-11-05 10:38:16.361866
INFO 11:38:16 visuals:__init__:L1154 Done loading boundaries: 2019-11-05 10:38:16.386127
WARNING 11:38:17 __init__:available_readers:L577 Could not import reader config from: ['/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/satpy/etc/readers/viirs_edr_flood.yaml']
WARNING 11:38:17 __init__:available_readers:L577 Could not import reader config from: ['/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/satpy/etc/readers/avhrr_l1b_gaclac.yaml']
WARNING 11:38:17 __init__:available_readers:L577 Could not import reader config from: ['/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/satpy/etc/readers/msi_safe.yaml']
WARNING 11:38:17 __init__:available_readers:L577 Could not import reader config from: ['/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/satpy/etc/readers/clavrx.yaml']
WARNING 11:38:17 __init__:available_readers:L577 Could not import reader config from: ['/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/satpy/etc/readers/caliop_l2_cloud.yaml']
WARNING 11:38:17 __init__:available_readers:L577 Could not import reader config from: ['/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/satpy/etc/readers/modis_l1b.yaml']
WARNING 11:38:18 __init__:available_readers:L577 Could not import reader config from: ['/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/satpy/etc/readers/modis_l2.yaml']
WARNING 11:38:18 __init__:available_readers:L577 Could not import reader config from: ['/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/satpy/etc/readers/avhrr_l1b_hrpt.yaml']
WARNING 11:38:18 __init__:available_readers:L577 Could not import reader config from: ['/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/satpy/etc/readers/li_l2.yaml']
INFO 11:38:19 __main__:__init__:L750 potential tracks already in database: ['IMAGE:toa_bidirectional_reflectance:C03: 0.85µm::SatPy:GOES_16:ABI:CONUS', 'IMAGE:toa_bidirectional_reflectance:C04: 1.37µm::SatPy:GOES_16:ABI:Mesoscale', 'IMAGE:toa_brightness_temperature:C10: 7.24µm::SatPy:GOES_16:ABI:Mesoscale', 'IMAGE:toa_bidirectional_reflectance:C05: 1.58µm::SatPy:GOES_16:ABI:Mesoscale', 'IMAGE:toa_brightness_temperature:C14:10.80µm::SatPy:GOES_16:ABI:Mesoscale', 'IMAGE:toa_brightness_temperature:C15:11.80µm::SatPy:GOES_16:ABI:Mesoscale', 'IMAGE:toa_brightness_temperature:C13:10.10µm::SatPy:GOES_16:ABI:Mesoscale', 'IMAGE:toa_brightness_temperature:C08: 5.77µm::SatPy:GOES_16:ABI:Mesoscale', 'IMAGE:toa_bidirectional_reflectance:C01: 0.45µm::SatPy:GOES_16:ABI:Mesoscale', 'IMAGE:toa_bidirectional_reflectance:C02: 0.59µm::SatPy:GOES_16:ABI:Mesoscale', 'IMAGE:toa_bidirectional_reflectance:C06: 2.23µm::SatPy:GOES_16:ABI:Mesoscale', 'IMAGE:toa_brightness_temperature:C16:13.00µm::SatPy:GOES_16:ABI:Mesoscale', 'IMAGE:toa_brightness_temperature:C07: 3.80µm::SatPy:GOES_16:ABI:Mesoscale', 'IMAGE:toa_brightness_temperature:C09: 6.75µm::SatPy:GOES_16:ABI:Mesoscale', 'IMAGE:toa_bidirectional_reflectance:C03: 0.85µm::SatPy:GOES_16:ABI:Mesoscale', 'IMAGE:toa_brightness_temperature:C12: 9.42µm::SatPy:GOES_16:ABI:Mesoscale', 'IMAGE:toa_brightness_temperature:C11: 8.30µm::SatPy:GOES_16:ABI:Mesoscale']
INFO 11:38:19 document:timeline_span:L555 document timeline Span is not set, using metadata extents
INFO 11:38:19 items:_time_extent_of_frames:L317 empty track cannot determine its horizontal extent
INFO 11:38:20 items:_time_extent_of_frames:L317 empty track cannot determine its horizontal extent
INFO 11:38:20 items:_time_extent_of_frames:L317 empty track cannot determine its horizontal extent
INFO 11:38:20 items:_time_extent_of_frames:L317 empty track cannot determine its horizontal extent
INFO 11:38:21 items:_time_extent_of_frames:L317 empty track cannot determine its horizontal extent
INFO 11:38:21 items:_time_extent_of_frames:L317 empty track cannot determine its horizontal extent
INFO 11:38:22 items:_time_extent_of_frames:L317 empty track cannot determine its horizontal extent
INFO 11:38:22 items:_time_extent_of_frames:L317 empty track cannot determine its horizontal extent
INFO 11:38:23 items:_time_extent_of_frames:L317 empty track cannot determine its horizontal extent
INFO 11:38:23 items:_time_extent_of_frames:L317 empty track cannot determine its horizontal extent
INFO 11:38:24 items:_time_extent_of_frames:L317 empty track cannot determine its horizontal extent
INFO 11:38:24 items:_time_extent_of_frames:L317 empty track cannot determine its horizontal extent
INFO 11:38:25 items:_time_extent_of_frames:L317 empty track cannot determine its horizontal extent
INFO 11:38:25 items:_time_extent_of_frames:L317 empty track cannot determine its horizontal extent
INFO 11:38:26 items:_time_extent_of_frames:L317 empty track cannot determine its horizontal extent
INFO 11:38:26 items:_time_extent_of_frames:L317 empty track cannot determine its horizontal extent
INFO 11:38:27 items:_time_extent_of_frames:L317 empty track cannot determine its horizontal extent
INFO 11:38:27 acceleratesupport:<module>:L17 No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
WARNING: Empty filename passed to function
WARNING 11:38:47 _qt:message_handler:L180 Empty filename passed to function
WARNING: QXcbConnection: XCB error: 3 (BadWindow), sequence: 2644, resource id: 35653436, major code: 40 (TranslateCoords), minor code: 0
WARNING 11:39:08 _qt:message_handler:L180 QXcbConnection: XCB error: 3 (BadWindow), sequence: 2644, resource id: 35653436, major code: 40 (TranslateCoords), minor code: 0
WARNING: Traceback (most recent call last):
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/uwsift/view/open_file_wizard.py", line 346, in remove_file
    if self.ui.fileList.isItemSelected(item):
AttributeError: 'QListWidget' object has no attribute 'isItemSelected'
WARNING 11:39:11 _qt:message_handler:L180 Traceback (most recent call last):
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/uwsift/view/open_file_wizard.py", line 346, in remove_file
    if self.ui.fileList.isItemSelected(item):
AttributeError: 'QListWidget' object has no attribute 'isItemSelected'
```

Full list of packages installed in environment:

```
# packages in environment at /media/nas/x21324/miniconda3/envs/py37_sandbox:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
affine                    2.3.0                      py_0    conda-forge
appdirs                   1.4.3                      py_1    conda-forge
asciitree                 0.3.3                      py_2    conda-forge
asn1crypto                1.2.0                    py37_0    conda-forge
attrs                     19.3.0                     py_0    conda-forge
bokeh                     1.3.4                    py37_0    conda-forge
boost-cpp                 1.70.0               h8e57a91_2    conda-forge
bzip2                     1.0.8                h516909a_1    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
cairo                     1.16.0            hfb77d84_1002    conda-forge
certifi                   2019.9.11                py37_0    conda-forge
cffi                      1.13.2           py37h8022711_0    conda-forge
cfitsio                   3.470                hb60a0a2_2    conda-forge
cftime                    1.0.4.2          py37hc1659b7_0    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cloudpickle               1.2.2                      py_0    conda-forge
configobj                 5.0.6                      py_0    conda-forge
cryptography              2.7              py37h72c5cf5_0    conda-forge
curl                      7.65.3               hf8cf82a_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.10.0           py37h516909a_0    conda-forge
dask                      2.6.0                      py_0    conda-forge
dask-core                 2.6.0                      py_0    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
distributed               2.6.0                      py_0    conda-forge
docutils                  0.15.2                   py37_0    conda-forge
eccodes                   2.14.1               hc4140ea_1    conda-forge
expat                     2.2.5             he1b5a44_1004    conda-forge
fasteners                 0.14.1                     py_3    conda-forge
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
freetype-py               2.1.0.post1                py_0    conda-forge
freexl                    1.0.5             h14c3975_1002    conda-forge
fsspec                    0.5.2                      py_0    conda-forge
geos                      3.7.2                he1b5a44_2    conda-forge
geotiff                   1.5.1                hfa9ff18_4    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
giflib                    5.1.7                h516909a_1    conda-forge
glib                      2.58.3            h6f030ca_1002    conda-forge
goesr                     0.5.2                    pypi_0    pypi
gst-plugins-base          1.14.5               h0935bb2_0    conda-forge
gstreamer                 1.14.5               h36ae1b5_0    conda-forge
h5py                      2.10.0          nompi_py37h513d04c_100    conda-forge
hdf4                      4.2.13            h9a582f1_1002    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.8                   py37_1000    conda-forge
imageio                   2.6.1                    py37_0    conda-forge
jasper                    1.900.1           h07fcdf6_1006    conda-forge
jinja2                    2.10.3                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
json-c                    0.13.1            h14c3975_1001    conda-forge
kealib                    1.4.10            h58c409b_1005    conda-forge
kiwisolver                1.1.0            py37hc9558a2_0    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libaec                    1.0.4                hf484d3e_0    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libclang                  9.0.0                hc9558a2_1    conda-forge
libcurl                   7.65.3               hda55be3_0    conda-forge
libdap4                   3.20.4               hd3bb157_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0  
libgdal                   3.0.1               h3d260b8_10    conda-forge
libgfortran-ng            7.3.0                hdf63c60_2    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
libkml                    1.3.0             h4fcabce_1010    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libllvm8                  8.0.1                hc9558a2_0    conda-forge
libllvm9                  9.0.0                hc9558a2_2    conda-forge
libnetcdf                 4.7.1           nompi_h94020b1_101    conda-forge
libopenblas               0.3.7                h6e990d7_2    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libpq                     11.5                 hd9ab2ff_1    conda-forge
libspatialite             4.3.0a            hcf5492f_1031    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.0.10            h57b8799_1003    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxkbcommon              0.9.1                hebb1f50_0    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
llvmlite                  0.30.0           py37h8b12597_1    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
markupsafe                1.1.1            py37h516909a_0    conda-forge
matplotlib                3.1.1                    py37_1    conda-forge
matplotlib-base           3.1.1            py37he7580a8_1    conda-forge
monotonic                 1.5                        py_0    conda-forge
msgpack-python            0.6.2            py37hc9558a2_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
netcdf4                   1.5.3            py37hf3213d6_0    conda-forge
nspr                      4.23                 he1b5a44_0    conda-forge
nss                       3.47                 he751ad9_0    conda-forge
numba                     0.46.0           py37hb3f55d8_1    conda-forge
numcodecs                 0.6.3            py37hf484d3e_0    conda-forge
numpy                     1.17.3           py37h95a1406_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openjpeg                  2.3.1                h21c5421_1    conda-forge
openssl                   1.1.1c               h516909a_0    conda-forge
packaging                 19.2                       py_0    conda-forge
pandas                    0.25.3           py37hb3f55d8_0    conda-forge
partd                     1.0.0                      py_0    conda-forge
pcre                      8.43                 he1b5a44_0    conda-forge
pillow                    6.2.1            py37h6b7be26_0    conda-forge
pip                       19.3.1                   py37_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
poppler                   0.67.0               ha967d66_7    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                11.5                 hc63931a_1    conda-forge
proj                      6.2.0                hc80f0dc_1    conda-forge
psutil                    5.6.3            py37h516909a_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pygrib                    2.0.4            py37hf3f1b0b_0    conda-forge
pykdtree                  1.3.1           py37hc1659b7_1002    conda-forge
pyopengl                  3.1.3b2                    py_1    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pyorbital                 1.5.0                      py_0    conda-forge
pyparsing                 2.4.2                      py_0    conda-forge
pyproj                    2.4.0            py37ha987037_0    conda-forge
pyqt                      5.12.3           py37hcca6a23_0    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtgraph                 0.10.0                     py_5    conda-forge
pyqtwebengine             5.12.1                   pypi_0    pypi
pyresample                1.13.2           py37hb3f55d8_0    conda-forge
pyshp                     2.1.0                      py_0    conda-forge
pysocks                   1.7.1                    py37_0    conda-forge
pyspectral                0.9.2                      py_0    conda-forge
python                    3.7.3                h33d41f4_1    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-geotiepoints       1.1.8            py37hd352d35_0    conda-forge
pytz                      2019.3                     py_0    conda-forge
pyyaml                    5.1.2            py37h516909a_0    conda-forge
qt                        5.12.5               hd8c4c69_1    conda-forge
quamash                   0.6.1                    pypi_0    pypi
rasterio                  1.1.0            py37h900e953_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.22.0                   py37_1    conda-forge
satpy                     0.17.1             pyhca3e704_0    conda-forge
scipy                     1.3.1            py37h921218d_2    conda-forge
setuptools                41.6.0                   py37_1    conda-forge
shapely                   1.6.4           py37hec07ddf_1006    conda-forge
six                       1.12.0                py37_1001    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
sqlalchemy                1.3.10           py37h516909a_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tbb                       2018.0.5             h2d50403_0    conda-forge
tblib                     1.4.0                      py_0    conda-forge
tiledb                    1.6.2                h69c774e_1    conda-forge
tk                        8.6.9             hed695b0_1003    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.3            py37h516909a_0    conda-forge
tqdm                      4.36.1                     py_0    conda-forge
trollimage                1.11.0                     py_0    conda-forge
trollsift                 0.3.3                      py_0    conda-forge
tzcode                    2019a             h516909a_1002    conda-forge
urllib3                   1.25.6                   py37_0    conda-forge
uwsift                    1.0.6                    pypi_0    pypi
vispy                     0.6.1            py37hf5ce8a7_0    conda-forge
wheel                     0.33.6                   py37_0    conda-forge
xarray                    0.14.0                     py_0    conda-forge
xerces-c                  3.2.2             h8412b87_1004    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.1.7             h14c3975_1001    conda-forge
zarr                      2.3.2                    py37_0    conda-forge
zict                      1.0.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.0                h3b9ef0a_0    conda-forge
```

Additional traceback when running `python -X faulthandler -m uwsift` and repeating the same:

```
Current thread 0x00007fe0901366c0 (most recent call first):
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/uwsift/__main__.py", line 924 in open_wizard
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/quamash/__init__.py", line 266 in run_forever
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/uwsift/__main__.py", line 1205 in main
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/uwsift/__main__.py", line 1210 in <module>
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/runpy.py", line 85 in _run_code
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/runpy.py", line 193 in _run_module_as_main
Aborted (core dumped)
```

**Comment by djhoese** [comment]
At least for this specific issue could you try from the master branch? @katherinekolman Fixed a bug very similar to this (if not the exact one) in a separate PR that may not be included in her export images test.

**Comment by djhoese** [comment]
@gerritholl The ABI CONUS geolocation issue (#252), and @katherinekolman's PR which included other fixes have all been merged to master. If you use the master branch my hope is that this will all work for you. Could you use the master branch and let me know? Thanks.

**Comment by gerritholl** [comment]
@djhoese With the master branch this problem there is no problem removing files from the dialogue.
