### ISSUE TITLE
'del' key to remove layers in 1.1.1 crashes SIFT if no layer is selected

### ISSUE THREAD

**Issue by ScottLindstrom** [ssec/sift#276]
I typically use 'del' to remove layers.  This works in 1.1.1 if a layer is highlighted.  If not, then SIFT aborts with:  IndexError: list index out of range

**Comment by djhoese** [comment]
Do you have the full traceback/error message?

**Comment by ScottLindstrom** [comment]
WARNING: Traceback (most recent call last):
  File "/home/scottl/anaconda3/envs/scottsift/lib/python3.7/site-packages/uwsift/__main__.py", line 543, in remove_layer
    uuids = list(uuids)
  File "/home/scottl/anaconda3/envs/scottsift/lib/python3.7/site-packages/uwsift/control/layer_tree.py", line 369, in current_selected_uuids
    yield self.doc.uuid_for_current_layer(q.row())
  File "/home/scottl/anaconda3/envs/scottsift/lib/python3.7/site-packages/uwsift/model/document.py", line 2380, in uuid_for_current_layer
    uuid = self.current_layer_set[row].uuid
  File "/home/scottl/anaconda3/envs/scottsift/lib/python3.7/site-packages/uwsift/model/document.py", line 212, in __getitem__
    return self._store[index]
IndexError: list index out of range
WARNING 15:53:35 _qt:message_handler:L187 Traceback (most recent call last):
  File "/home/scottl/anaconda3/envs/scottsift/lib/python3.7/site-packages/uwsift/__main__.py", line 543, in remove_layer
    uuids = list(uuids)
  File "/home/scottl/anaconda3/envs/scottsift/lib/python3.7/site-packages/uwsift/control/layer_tree.py", line 369, in current_selected_uuids
    yield self.doc.uuid_for_current_layer(q.row())
  File "/home/scottl/anaconda3/envs/scottsift/lib/python3.7/site-packages/uwsift/model/document.py", line 2380, in uuid_for_current_layer
    uuid = self.current_layer_set[row].uuid
  File "/home/scottl/anaconda3/envs/scottsift/lib/python3.7/site-packages/uwsift/model/document.py", line 212, in __getitem__
    return self._store[index]
IndexError: list index out of range
Aborted

**Comment by djhoese** [comment]
Interestingly this was partially fixed by #240 but that only helps when there were never any layers loaded. Still investigating what the right fix for this might be.

**Comment by ameraner** [comment]
Closing this as the layers removal has been reworked and fixed in SIFT 2.0.
