### ISSUE TITLE
No module named 'PyQt5.QtWebEngineWidgets'

### ISSUE THREAD

**Issue by PedroVenancio** [ssec/sift#432]
I'm trying to install SIFT on a fresh Ubuntu 24.04.1 with Miniforge, following the instructions: https://sift.readthedocs.io/en/latest/installation.html#installing-with-conda

Everything seems to be fine, but when I run SIFT GUI I get:

```
(sift_env) pedro@omen:~$ python -m uwsift
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/pedro/miniforge3/envs/sift_env/lib/python3.12/site-packages/uwsift/__main__.py", line 39, in <module>
    from uwsift.control.layer_tree import LayerStackTreeViewModel
  File "/home/pedro/miniforge3/envs/sift_env/lib/python3.12/site-packages/uwsift/control/layer_tree.py", line 47, in <module>
    from uwsift.view.colormap_dialogs import ChangeColormapDialog
  File "/home/pedro/miniforge3/envs/sift_env/lib/python3.12/site-packages/uwsift/view/colormap_dialogs.py", line 6, in <module>
    from uwsift.ui.change_colormap_dialog_ui import Ui_changeColormapDialog
  File "/home/pedro/miniforge3/envs/sift_env/lib/python3.12/site-packages/uwsift/ui/change_colormap_dialog_ui.py", line 81, in <module>
    from uwsift.ui.custom_widgets import QNoScrollDoubleSpinBox
  File "/home/pedro/miniforge3/envs/sift_env/lib/python3.12/site-packages/uwsift/ui/custom_widgets.py", line 3, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'
```

This issue seems related to https://github.com/ssec/sift/issues/233

**Comment by ameraner** [comment]
Hi @PedroVenancio , if you are installing from conda, you are getting an old version of SIFT (likely v1.2.3), since the latest v2 is not yet released on conda as it is still in beta status. The issue is likely solved on v2, so I would suggest to try to install the latest SIFT from github directly, following the instructions here: https://sift.readthedocs.io/en/latest/dev_guide/contributing.html#dev-install . Please let us know how that goes!

**Comment by lmeru** [comment]
Hi @ameraner, I have a problem similar to that described by @PedroVenancio, but I haven't try to install the latest yet (yes, my version loaded from conda-forge is v 1.2.3). I'll try to do it asap.
Here's a brief report of what I tried, sent before to Dave Hoese that re-addressed me here:
I've created a fresh sift_env (with miniforge) and when I try to run sift from the activated sift_env  with the command python -m uwsift as described in https://sift.readthedocs.io/en/latest/installation.html
I obtain the following:
(sift_env) luca@zeta-X1:~$ python -m uwsift
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/luca/miniforge3/envs/sift_env/lib/python3.12/site-packages/uwsift/__main__.py", line 39, in <module>
    from uwsift.control.layer_tree import LayerStackTreeViewModel
  File "/home/luca/miniforge3/envs/sift_env/lib/python3.12/site-packages/uwsift/control/layer_tree.py", line 47, in <module>
    from uwsift.view.colormap_dialogs import ChangeColormapDialog
  File "/home/luca/miniforge3/envs/sift_env/lib/python3.12/site-packages/uwsift/view/colormap_dialogs.py", line 6, in <module>
    from uwsift.ui.change_colormap_dialog_ui import Ui_changeColormapDialog
  File "/home/luca/miniforge3/envs/sift_env/lib/python3.12/site-packages/uwsift/ui/change_colormap_dialog_ui.py", line 81, in <module>
    from uwsift.ui.custom_widgets import QNoScrollDoubleSpinBox
  File "/home/luca/miniforge3/envs/sift_env/lib/python3.12/site-packages/uwsift/ui/custom_widgets.py", line 3, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

I then tried with this:
(sift_env) luca@zeta-X1:~$ mamba install PyQtWebEngine

obtaining:
(sift_env) luca@zeta-X1:~$ python3 -m uwsift
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/luca/miniforge3/envs/sift_env/lib/python3.12/site-packages/uwsift/__main__.py", line 54, in <module>
    from uwsift.view.scene_graph import SceneGraphManager
  File "/home/luca/miniforge3/envs/sift_env/lib/python3.12/site-packages/uwsift/view/scene_graph.py", line 50, in <module>
    from uwsift.view.visuals import (NEShapefileLines, TiledGeolocatedImage, RGBCompositeLayer, PrecomputedIsocurve)
  File "/home/luca/miniforge3/envs/sift_env/lib/python3.12/site-packages/uwsift/view/visuals.py", line 34, in <module>
    from vispy.gloo.texture import should_cast_to_f32
ImportError: cannot import name 'should_cast_to_f32' from 'vispy.gloo.texture' (/home/luca/miniforge3/envs/sift_env/lib/python3.12/site-packages/vispy/gloo/texture.py)

**Comment by lmeru** [comment]
Hi @ameraner this is what I obtained trying to install the beta version following the instructions on https://sift.readthedocs.io/en/latest/dev_guide/contributing.html#dev-install : 
(sift_env) luca@zeta-X1:~$ pip install git+https://github.com/ssec/sift.git
Collecting git+https://github.com/ssec/sift.git
  Cloning https://github.com/ssec/sift.git to /tmp/pip-req-build-c4caprsj
  Running command git clone --filter=blob:none --quiet https://github.com/ssec/sift.git /tmp/pip-req-build-c4caprsj
  Resolved https://github.com/ssec/sift.git to commit 6a4aa6d76e0b429d17258c4fdce89ea96e61d1ad
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: appdirs in ./miniforge3/envs/sift_env/lib/python3.12/site-packages (from uwsift==2.0.0b1) (1.4.4)
Requirement already satisfied: donfig>=0.8.1 in ./miniforge3/envs/sift_env/lib/python3.12/site-packages (from uwsift==2.0.0b1) (0.8.1.post1)
Requirement already satisfied: h5py in ./miniforge3/envs/sift_env/lib/python3.12/site-packages (from uwsift==2.0.0b1) (3.12.1)
Requirement already satisfied: imageio in ./miniforge3/envs/sift_env/lib/python3.12/site-packages (from uwsift==2.0.0b1) (2.36.0)
Collecting av (from uwsift==2.0.0b1)
  Using cached av-13.1.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.4 kB)
Requirement already satisfied: matplotlib in ./miniforge3/envs/sift_env/lib/python3.12/site-packages (from uwsift==2.0.0b1) (3.9.2)
Requirement already satisfied: netCDF4 in ./miniforge3/envs/sift_env/lib/python3.12/site-packages (from uwsift==2.0.0b1) (1.7.1)
Requirement already satisfied: numba in ./miniforge3/envs/sift_env/lib/python3.12/site-packages (from uwsift==2.0.0b1) (0.60.0)
Requirement already satisfied: numpy in ./miniforge3/envs/sift_env/lib/python3.12/site-packages (from uwsift==2.0.0b1) (2.0.2)
Requirement already satisfied: pillow in ./miniforge3/envs/sift_env/lib/python3.12/site-packages (from uwsift==2.0.0b1) (11.0.0)
Requirement already satisfied: pyproj in ./miniforge3/envs/sift_env/lib/python3.12/site-packages (from uwsift==2.0.0b1) (3.7.0)
Requirement already satisfied: pyqt5>=5.15 in ./miniforge3/envs/sift_env/lib/python3.12/site-packages (from uwsift==2.0.0b1) (5.15.9)
Requirement already satisfied: pyqtgraph in ./miniforge3/envs/sift_env/lib/python3.12/site-packages (from uwsift==2.0.0b1) (0.13.7)
Requirement already satisfied: pyqtwebengine in ./miniforge3/envs/sift_env/lib/python3.12/site-packages (from uwsift==2.0.0b1) (5.15.4)
Requirement already satisfied: pyshp in ./miniforge3/envs/sift_env/lib/python3.12/site-packages (from uwsift==2.0.0b1) (2.3.1)
Requirement already satisfied: pyyaml in ./miniforge3/envs/sift_env/lib/python3.12/site-packages (from uwsift==2.0.0b1) (6.0.2)
Requirement already satisfied: rasterio in ./miniforge3/envs/sift_env/lib/python3.12/site-packages (from uwsift==2.0.0b1) (1.4.1)
Requirement already satisfied: satpy in ./miniforge3/envs/sift_env/lib/python3.12/site-packages (from uwsift==2.0.0b1) (0.52.0)
Requirement already satisfied: scikit-image in ./miniforge3/envs/sift_env/lib/python3.12/site-packages (from uwsift==2.0.0b1) (0.24.0)
Requirement already satisfied: shapely in ./miniforge3/envs/sift_env/lib/python3.12/site-packages (from uwsift==2.0.0b1) (2.0.6)
Requirement already satisfied: sqlalchemy in ./miniforge3/envs/sift_env/lib/python3.12/site-packages (from uwsift==2.0.0b1) (2.0.36)
Requirement already satisfied: trollsift in ./miniforge3/envs/sift_env/lib/python3.12/site-packages (from uwsift==2.0.0b1) (0.5.1)
Requirement already satisfied: vispy>=0.10.0 in ./miniforge3/envs/sift_env/lib/python3.12/site-packages (from uwsift==2.0.0b1) (0.14.3)
INFO: pip is looking at multiple versions of uwsift to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement ecmwflibs (from uwsift) (from versions: none)
ERROR: No matching distribution found for ecmwflibs

**Comment by ameraner** [comment]
Ah, that is because there are no ecmwflibs wheels for python 3.12 - in the setup.py we limit to <=3.11 (https://github.com/ssec/sift/blob/master/setup.py#L230C5-L230C99). Can you please try with a py3.11 environment? then it should finally work :)

**Comment by lmeru** [comment]
Hi Andrea,

still something to be fixed after the python 3.11 installation:

(sift_env) ***@***.***:~$ python -m uwsift
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File
"/home/luca/miniforge3/envs/sift_env/lib/python3.11/site-packages/uwsift/__main__.py",
line 54, in <module>
    from uwsift.view.scene_graph import SceneGraphManager
  File
"/home/luca/miniforge3/envs/sift_env/lib/python3.11/site-packages/uwsift/view/scene_graph.py",
line 50, in <module>
    from uwsift.view.visuals import (NEShapefileLines,
TiledGeolocatedImage, RGBCompositeLayer, PrecomputedIsocurve)
  File
"/home/luca/miniforge3/envs/sift_env/lib/python3.11/site-packages/uwsift/view/visuals.py",
line 34, in <module>
    from vispy.gloo.texture import should_cast_to_f32
ImportError: cannot import name 'should_cast_to_f32' from
'vispy.gloo.texture'
(/home/luca/miniforge3/envs/sift_env/lib/python3.11/site-packages/vispy/gloo/texture.py)

Does this help?
Luca



*Luca Merucci, Ph.D.*

*Istituto Nazionale di Geofisica e Vulcanologia*

*Via di Vigna Murata, 605*

*00143 Roma (Italia)*




*tel. +39 0651860539*


Il giorno lun 28 ott 2024 alle ore 13:18 Andrea Meraner <
***@***.***> ha scritto:

**Comment by ameraner** [comment]
@PedroVenancio : you can find bundles for Linux here: https://bin.ssec.wisc.edu/pub/sift/dist/experimental/ , e.g. https://bin.ssec.wisc.edu/pub/sift/dist/experimental/SIFT_2.0.0b1dev_linux_20241011_150832.tar.gz

@lmeru : did you install sift from conda in the new py3.11 env? I am wondering since the failing line was removed almost two years ago from master, so looks like you're still using an old version of SIFT: https://github.com/ssec/sift/commit/9428ddbf8df9ad90f7887e18c84c9dc373b2c27e .

**Comment by lmeru** [comment]
Hi Andrea
I can't answer you now: yesterday I tried to follow the Pedro Venancio
suggestion and I downgraded the env to python 3.10 and installed all the
libs that he had indicated in his last email. That installation works.

I can try to make a fresh new env with python 3.11 following your
indications, and checking the sift version.
When do you think vSIFT 2.0 will be released on conda-forge?

L.





*Luca Merucci, Ph.D.*

*Istituto Nazionale di Geofisica e Vulcanologia*

*Via di Vigna Murata, 605*

*00143 Roma (Italia)*




*tel. +39 0651860539*


Il giorno mer 30 ott 2024 alle ore 12:25 Andrea Meraner <
***@***.***> ha scritto:

**Comment by benscarlson** [comment]
Hello,

I received the same PyQt5 error and eventually found this issue. The discussion helped me to finally find a solution, which was to install python 3.11 using conda and install uwsift using pip.

```bash
# Install on Red Hat 8

conda create -n sift_env_311 -c conda-forge --strict-channel-priority python=3.11

conda activate sift_env_311

pip install git+https://github.com/ssec/sift.git
# Can also try installing the package version from pip
# pip install uwsift

# Try installing hdf5pugin during the conda install
pip install hdf5plugin dask[dataframe] defusedxml pyspectral rioxarray pyhdf pygac PyQtChart
```

I think it would be helpful if the package maintainers either updated the version on Conda or adjusted the installation [documentation](https://sift.readthedocs.io/en/latest/installation.html) since following the instructions to install via Conda no longer works.
